// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubgwfioejghmfrlyrumf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViZ3dmaW9lamdobWZybHlydW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTc5MzksImV4cCI6MjA3MDM5MzkzOX0.cJxplan5C9pOXQM1IO3YIDyVgxAf9so5p5_Cxbek_m0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});